### ISSUE TITLE
MDA Position buttons (Add/Remove/Clear) are non-functional

### ISSUE THREAD

**Issue by ianhi** [tlambert03/napari-micromanager#23]
On current `main` the position buttons don't render properly and also don't respond when I click them:

![image](https://user-images.githubusercontent.com/10111092/125475896-df7b6d1e-87b0-4f78-979d-1b2820dd87c8.png)

**Comment by tlambert03** [comment]
if you enable the group do they work? (the checkbox next to "Stage Positions")?

**Comment by ianhi** [comment]
> (the checkbox next to "Stage Positions")?

:O I never saw that until now! It camouflaged so well. Is there an easy way to change the styling to make that more visible? I truly don't think I would have noticed that without it being pointed out to me.

**Comment by tlambert03** [comment]
this is probably an OS-specific issue in the napari stylesheet (and should be fixed in napari).  We don't use [QGroupBox](https://doc.qt.io/qt-5/qgroupbox.html) much over there.  looks like this on mac:

![Screen Shot 2021-07-15 at 11 33 46 AM](https://user-images.githubusercontent.com/1609449/125815648-33ebe5f8-3e9b-478f-95a5-79548ab67df2.png)

**Comment by ianhi** [comment]
Closing to be dealt with in napari
